development:
  adapter: postgresql
  database: benjaminsoft_dev
  username: postgres
  password: r,H+1,kea

production:
  adapter: postgresql
  database: benjaminsoft_production
  username: postgres
  password: r,H+1,kea

test:
  adapter: postgresql
  database: benjaminsoft_test
  username: postgres
  password: r,H+1,kea
